services:
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: university
      MYSQL_USER: university
      MYSQL_PASSWORD: university
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts # Use the official Jenkins LTS image
    privileged: true # Required for Docker-in-Docker functionality within Jenkins if needed
    user: root # Run Jenkins as root to avoid permission issues, especially with Docker-in-Docker
    ports:
      - "8080:8080" # Jenkins web interface
      - "50000:50000" # Jenkins agent communication port
    volumes:
      - jenkins_home:/var/jenkins_home # Persistent storage for Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket for Docker-in-Docker
      - /usr/local/bin/docker:/usr/local/bin/docker # Mount Docker client binary for Docker-in-Docker
    environment:
      - JENKINS_OPTS="--prefix=/jenkins" # Optional: Set a context path if reverse proxying
    restart: unless-stopped # Ensure Jenkins restarts automatically

volumes:
  jenkins_home: # Define the named volume for Jenkins data
  db_data:

networks:
  app-network: