services:
  php-apache-environment:
    container_name: php-apache
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./html:/var/www/html/
    ports:
      - 80:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
  db:
    container_name: db
    image: mysql
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: university
      MYSQL_PASSWORD: university
  jenkins:
    image: jenkins/jenkins:lts # Use the official Jenkins LTS image
    privileged: true # Required for Docker-in-Docker functionality within Jenkins if needed
    user: root # Run Jenkins as root to avoid permission issues, especially with Docker-in-Docker
    ports:
      - "8080:8080" # Jenkins web interface
      - "50000:50000" # Jenkins agent communication port
    volumes:
      - jenkins_home:/var/jenkins_home # Persistent storage for Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket for Docker-in-Docker
      - /usr/local/bin/docker:/usr/local/bin/docker # Mount Docker client binary for Docker-in-Docker
    environment:
      - JENKINS_OPTS="--prefix=/jenkins" # Optional: Set a context path if reverse proxying
    restart: unless-stopped # Ensure Jenkins restarts automatically

volumes:
  jenkins_home: # Define the named volume for Jenkins data